"""
generator.py — the deterministic "hands" of the builder agent.

Nothing here needs an LLM. Given a dashboard *spec* (a dict) it produces a
self-contained, offline dashboard folder by reusing the verified renderer
engine and only swapping in spec.js + data.js. It also writes the fillable
Excel template from the spec's data model, and reads filled workbooks back.

These functions are exposed to the Strands agent as tools (see tools.py),
but they are plain Python and can be run / tested on their own.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

# The engine source. Prefer the copy bundled inside this folder (agent/template),
# so the agent is self-contained and portable. Fall back to the repo's renderer/
# when running in-tree without a bundled template.
HERE = Path(__file__).resolve().parent
_BUNDLED = HERE / "template"
RENDERER = _BUNDLED if (_BUNDLED / "engine.js").exists() else HERE.parent / "renderer"

# files copied verbatim from the renderer (the engine never changes per project)
_STATIC_FILES = ["index.html", "styles.css", "engine.js"]


def generate_dashboard(spec: dict[str, Any], data: dict[str, list[dict]], out_dir: str | Path) -> str:
    """Assemble a self-contained dashboard at out_dir from a spec + embedded data.

    The result opens with no internet and no Python — just index.html.
    Returns the absolute path to the generated folder.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    # 1. copy the unchanging engine + styles + shell
    for f in _STATIC_FILES:
        shutil.copy2(RENDERER / f, out / f)
    # 2. copy vendored libraries (offline)
    vendor_src, vendor_dst = RENDERER / "vendor", out / "vendor"
    if vendor_dst.exists():
        shutil.rmtree(vendor_dst)
    shutil.copytree(vendor_src, vendor_dst)

    # 3. write the per-project spec and data
    (out / "spec.js").write_text(
        "/* generated by the builder agent */\nwindow.DASHBOARD_SPEC = "
        + json.dumps(spec, indent=2) + ";\n", encoding="utf-8")
    (out / "data.js").write_text(
        "/* embedded sample data so the dashboard works offline on first open */\n"
        "window.SAMPLE_DATA = " + json.dumps(data, indent=2) + ";\n", encoding="utf-8")

    return str(out.resolve())


def write_excel_template(spec: dict[str, Any], out_path: str | Path) -> str:
    """Write a fillable .xlsx template from spec['dataModel'].

    Adds an Instructions sheet, then one sheet per table with bold headers,
    a frozen header row, and a couple of example rows. Returns the path.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment

    model = spec.get("dataModel") or {}
    sheets = model.get("sheets") or []
    if not sheets:
        raise ValueError("spec['dataModel']['sheets'] is empty — nothing to template.")

    wb = Workbook()
    # ---- Instructions sheet ----
    ws = wb.active
    ws.title = "Instructions"
    ws["A1"] = f"{spec.get('title', 'Dashboard')} — data template"
    ws["A1"].font = Font(bold=True, size=14)
    lines = [
        "",
        "Fill the other tabs with your data, then upload this file in the dashboard.",
        "Keep the sheet names and the header row (row 1) exactly as they are.",
        "Rows below the header can be anything; add as many as you need.",
        "",
        "Sheets in this workbook:",
    ]
    for i, sh in enumerate(sheets):
        lines.append(f"  • {sh['name']} — {sh.get('description', '')}")
    for r, text in enumerate(lines, start=2):
        ws[f"A{r}"] = text
    ws.column_dimensions["A"].width = 90

    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="1F5FA8")

    # ---- one sheet per table ----
    for sh in sheets:
        s = wb.create_sheet(title=sh["name"][:31])
        cols = sh.get("columns", [])
        for c, col in enumerate(cols, start=1):
            cell = s.cell(row=1, column=c, value=col["name"])
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="left")
            s.column_dimensions[cell.column_letter].width = max(12, len(col["name"]) + 4)
            # comment-style hint via column header note
            desc = col.get("description")
            if desc:
                from openpyxl.comments import Comment
                cell.comment = Comment(desc, "template")
        # two example rows from the column examples
        for ex_row in range(2, 4):
            for c, col in enumerate(cols, start=1):
                if "example" in col:
                    s.cell(row=ex_row, column=c, value=col["example"])
        s.freeze_panes = "A2"

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    return str(out.resolve())


def read_workbook(path: str | Path) -> dict[str, list[dict]]:
    """Read a filled .xlsx into {sheet_name: [row_dicts]} (header row = keys).

    Skips the Instructions sheet and any fully-empty rows.
    """
    from openpyxl import load_workbook

    wb = load_workbook(path, data_only=True)
    out: dict[str, list[dict]] = {}
    for name in wb.sheetnames:
        if name.lower() == "instructions":
            continue
        ws = wb[name]
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            out[name] = []
            continue
        headers = [h for h in rows[0]]
        records = []
        for r in rows[1:]:
            if all(v is None for v in r):
                continue
            rec = {}
            for h, v in zip(headers, r):
                if h is None:
                    continue
                rec[str(h)] = v
            if rec:
                records.append(rec)
        out[name] = records
    return out


# ---- tiny CLI for manual testing: python generator.py <spec.json> <data.xlsx> <out_dir> ----
if __name__ == "__main__":
    import sys

    spec_path, data_path, out_dir = sys.argv[1], sys.argv[2], sys.argv[3]
    spec = json.loads(Path(spec_path).read_text())
    data = read_workbook(data_path)
    folder = generate_dashboard(spec, data, out_dir)
    tmpl = write_excel_template(spec, Path(out_dir) / "template.xlsx")
    print("dashboard ->", folder)
    print("template  ->", tmpl)
